### ISSUE TITLE
zengxs/gitlab:ee and zengxs/gitlab:latest not update on docker hub

### ISSUE THREAD

**Issue by Sampozzo** [zengxs/gitlab-arm64#82]
I used in my compose untill now the zengxs/gitlab:ee image but with 16.10.1 it is not updated, and also the latest.

I had to switch my compose to zengxs/gitlab:ee-amd64. Can i know why?

**Comment by zengxs** [comment]
It seems that the issue is caused by a conflict between the new version of docker buildx and docker manifest, which has disrupted the multi-architecture image push process. (https://github.com/docker/buildx/issues/1509)

Additionally, this did not trigger a failure in the CI, so I had not noticed the problem before.
Let me figure out a way to fix this issue.

**Comment by Sampozzo** [comment]
Thanks for the reply @zengxs. It is not a problem as I think we are all here for the arm image. Thank you!

**Comment by zengxs** [comment]
In the latest build, the multi-architecture images have been successfully pushed to Docker Hub, so I believe this issue has been resolved.

Thank you for using the image and for reporting the issue. ❤️
